### ISSUE TITLE
Is babel.server.config.js used? I can 't see how.

### ISSUE THREAD

**Issue by fivethreeo** [sibelius/react-server-components-playground#5]
# No Template

👉 Please follow one of the issue templates provided by the repo - if you are seeing this message, it means you haven't.

If you don't follow the issue template, we may immediately close it.

**Comment by sibelius** [comment]
it is missing in the repo

but it should be like this

https://github.com/sibelius/react-webpack-ssr-boilerplate/blob/master/webpack.server.config.js#L48

**Comment by fivethreeo** [comment]
Ah, thought I was being dense ;)

**Comment by sibelius** [comment]
let me know if you have more doubts about the code
